# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20170912_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='option',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
